---
kind: pipeline
type: kubernetes
name: callisto-ui

platform:
  os: linux
  arch: amd64

steps:
  - name: install dependencies
    image: &node-version
      # The version we're targeting for production
      node:14.15.4-alpine
    environment:
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
    commands: 
     - npm install

  - name: lint project
    image: quay.io/ukhomeofficedigital/node-artifactory:14
    environment:
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
    commands: 
      - npm run lint
      - npx stylelint "**/*.scss"
    depends_on: 
      - install dependencies

  - name: test project
    image: quay.io/ukhomeofficedigital/node-artifactory:14
    environment:
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
    commands:
      - npm run test
    depends_on:
      - install dependencies

  - name: build project
    image: quay.io/ukhomeofficedigital/node-artifactory:14
    environment:
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
    commands:
      - npm run build
    depends_on:
      - install dependencies
